# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - eatinout-web

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js
      - name: Build project
        run: npm run build

      # 5️⃣ Debug: Check .next folder
      - name: Check build output
        run: ls -la .next

      # 6️⃣ Copy public folder
      - name: Copy public folder
        run: cp -r public .next/standalone/

      # 7️⃣ Copy Next static files (IMPORTANT FIX)
      - name: Copy static folder
        run: |
          mkdir -p .next/standalone/.next
          cp -r .next/static .next/standalone/.next/
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eatinout-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6E5C4915EE2741D0971D9FB9163D2E62 }}
          package: .next/standalone